# YouTube-ish navigation
Shift+RIGHT    seek 30
Shift+LEFT     seek -30
Alt+RIGHT      add volume 5
Alt+LEFT       add volume -5
`              cycle-values speed 0.5 0.75 1 1.25 1.5 2

# Track switching
Shift+a        cycle audio
Shift+s        cycle sub
Shift+f        cycle fullscreen
f              cycle fullscreen
m              cycle mute

# Playlist / files
<              playlist-prev
>              playlist-next

# Screenshots (see scripts/screenshot.lua)
s              script-binding screenshot/save
Shift+v        script-binding screenshot/copy
Shift+w        script-binding screenshot/copy-video
