#!/usr/bin/env bash

# Download and install nvm:
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.1/install.sh | bash

# Download and install Node.js:
nvm install node

# deno
curl -fsSL https://deno.land/install.sh | sh

# bun
curl -fsSL https://bun.sh/install | bash
