[tools]
antigravity-cli = "latest"
"aqua:modem-dev/hunk" = "latest"
codex = "latest"
go = "1.27.0"
opencode = "latest"
pi = "latest"
pnpm = "latest"
ruby = "latest"

[settings]
idiomatic_version_file_enable_tools = ["ruby"]

[settings.ruby]
compile = false

[settings.upgrade]
auto_prune = false
