[tools]
antigravity-cli = "latest"
"aqua:modem-dev/hunk" = "latest"
codex = "latest"
go = "latest"
opencode = "latest"
pi = "latest"
pnpm = "12.0.0"
ruby = "latest"

[settings]
idiomatic_version_file_enable_tools = ["ruby"]

[settings.ruby]
compile = false
