#!/usr/bin/env bash

add-apt-repository ppa:git-core/ppa
sudo apt install git tmux snapd

git config --global user.email "programmer.pranjal@gmail.com"
git config --global user.name "MandavkarPranjal"

# install neovim from snap
sudo snap install nvim --classic
