#!/usr/bin/env bash

git config --global user.email "programmer.pranjal@gmail.com"
git config --global user.name "MandavkarPranjal"

sudo apt install tmux snapd

# install neovim from snap
sudo snap install nvim --classic
