#!/usr/bin/env bash
set -e

# install ghostty from snap
sudo snap install ghostty --classic

# install fonts from brew
brew install --cask font-fira-mono-nerd-font
brew install --cask font-jetbrains-mono-nerd-font
