#!/usr/bin/env bash
set -e

sudo apt-get install -y \
    git \
    ripgrep \
    fd-find \
    gh \
    xclip \
    python3-pip \
    openssh-client \
    stow \
    nfs-common \

# zoxide
curl -sSfL https://raw.githubusercontent.com/ajeetdsouza/zoxide/main/install.sh | sh

# instaling some brew
brew install fzf
brew install bat
brew install lazygit
brew install tldc
brew install git-delta
brew install pnpm
brew install daytonaio/cli/daytona
brew install fastfetch

# update tldr cache for offline usage
tldr --update

# installign screenshot tools
sudo apt install maim xclip
